network:
  mm: byol+clf+mse
  feature_dim: 1024
  depth: 16
  heads: 10
  dim_feedforward: 3096
  clf_mask: 10
  mse_mask: 5

saving:
  log_dir: logs/log_all_run3
  checkpoint_dir: checkpoints/checkpoint_all_run3
  n_epochs: 100

trainer:
  batch_size: 64
  m: 0.996 # momentum update
  max_epochs: 10000
  num_workers: 8
  acc_lambda: 0.1
  mse_lambda: 10
  warmup_epochs: 10

optimizer:
  lr: 0.0003
  weight_decay: 0.00005

data:
  path: /userhome/timeinvariant/run3/
  mask_way: mask_per
  time_mask: 10
  time_len: 30
  
