network:
  mm: byol+clf+mse
  feature_dim: 1024
  depth: 32
  heads: 20
  dim_feedforward: 4096
  clf_mask: 10
  mse_mask: 5

saving:
  log_dir: logs/log_big
  checkpoint_dir: checkpoints/big
  n_epochs: 100

trainer:
  batch_size: 32
  m: 0.996 # momentum update
  max_epochs: 100000
  num_workers: 8
  acc_lambda: 5
  mse_lambda: 200
  warmup_epochs: 10

optimizer:
  lr: 0.0003
  weight_decay: 0.00005

data:
  path: /userhome/timeinvariant/timeseries/
  mask_way: mask_per
  time_mask: 10
  time_len: 30
  
